"""Build the app's copy of the website's altar artwork.

The website's originals in ../assets/altar are ~86 MB of full-size PNGs. The
app bundles small WebP copies instead (same folder layout, .webp extension) so
the altar works offline and Expo Go / EAS Update downloads stay small, and
writes src/lib/altar/assetManifest.ts mapping each website path to its copy.

Run from app/:  python3 scripts/build-altar-assets.py   (needs Pillow)
"""
import os
from pathlib import Path

from PIL import Image

APP = Path(__file__).resolve().parent.parent
SRC = APP.parent / "assets" / "altar"
OUT = APP / "assets" / "altar"
MANIFEST = APP / "src" / "lib" / "altar" / "assetManifest.ts"

# The 13 MB pentagram cloth and wooden-altar2 are not offered by the website's
# cabinet; saves that use them fall back to the website URL.
SKIP = {"objects/cloths/black-pentagram.png", "wooden-altar2.png"}

entries = []
for path in sorted(SRC.rglob("*")):
    if not path.is_file() or path.suffix.lower() != ".png":
        continue
    rel = path.relative_to(SRC).as_posix()
    if rel in SKIP:
        continue
    is_background = rel.startswith("backgrounds/")
    limit = 1600 if is_background else 512
    image = Image.open(path)
    original_size = image.size
    image.thumbnail((limit, limit), Image.LANCZOS)
    target = OUT / Path(rel).with_suffix(".webp")
    target.parent.mkdir(parents=True, exist_ok=True)
    if is_background:
        image.convert("RGB").save(target, "WEBP", quality=78, method=4)
    else:
        image.save(target, "WEBP", quality=82, method=4)
    entries.append((f"assets/altar/{rel}", target.relative_to(APP).as_posix(), original_size))

lines = [
    "// Generated by scripts/build-altar-assets.py. Do not edit by hand.",
    "// Website asset path (as saved in altar JSON, without ../ or leading /) to",
    "// the app's bundled WebP copy and the website original's pixel size (the",
    "// website sizes each object box from the image's natural aspect ratio).",
    "/* eslint-disable */",
    "",
    "export const bundledAltarAssets: Record<string, { source: number; width: number; height: number }> = {",
]
for web, local, (w, h) in entries:
    lines.append(f"  '{web}': {{ source: require('../../../{local}'), width: {w}, height: {h} }},")
lines += ["};", ""]
MANIFEST.parent.mkdir(parents=True, exist_ok=True)
MANIFEST.write_text("\n".join(lines))
total = sum(os.path.getsize(APP / local) for _, local, _ in entries)
print(f"{len(entries)} assets, {total / 1024 / 1024:.1f} MB")
